### ISSUE TITLE
Lack of availability in nexus/maven central makes for difficult integration into existing projects

### ISSUE THREAD

**Issue by amckee23** [richmartin/detox#1]
Hi, 

I have been looking at detox and it looks great, however until it makes it into one of the public repositories it is difficult for us to integrate it into any of our projects.

Is there a plan for this to be released into central?

Many Thanks

Andy

**Comment by richmartin** [comment]
There is indeed! In fact we supposedly have everything set up to push it to maven central but are just dealing with some permission issue. You can follow the issue's bug here: https://issues.sonatype.org/browse/OSSRH-19340

When the maven central build is ready, I'll close this bug with the link.

**Comment by amckee23** [comment]
Perfect +1 for the speedy response!  

A

**Comment by richmartin** [comment]
Detox is now available in Maven Central as the artefact com.moozvine:detox:1.0.1
